### PR TITLE
Add Stride package

### PR DESCRIPTION
**Pull request by itn3000**
This PR adds extension for R3 integration with [Stride](https://www.stride3d.net/).
Usage is described in src/R3.Stride/README.md.

Currently, there are problem described in below;

* disable assembly signing because build failure related to Stride build task
* do not implement functions for creating `Observable<T>` from UI events yet
    * Should implement after merge or before merge?

### CODE REVIEW

**Comment by itn3000** [comment]
should I implement UI extension before merge?

**Comment by neuecc** [comment]
Thank you, I've run in my environment.
If the UI extension is already completed, I would like to merge it and release together.
(However, there is an issue with the NuGet upload so upload to be delayed.)

**Comment by itn3000** [comment]
UI implementation has done, ready for review

**Comment by neuecc** [comment]
Thank you, it's well implemented and very helpful!
I would like to release.

Additionally, regarding the package name, there have been issues with NuGet, and as a result of negotiations, we will go with R3Extension.Stride (same applies to others).

**Pull request merged**
