### PR TITLE
Add Merge operators

### PR DESCRIPTION
**Pull request by TORISOUP**
Add `Merge(IEnumerable<Observable<T>>)` and `Merge(params Observable<T>[] targets)` operators

### CODE REVIEW

**Comment by neuecc** [comment]
This concat looks a bit unnatural.  
Instead, wouldn't it be sufficient to change it to  
`public static Observable<T> Merge<T>(this IEnumerable<Observable<T>> sources)`?

**Comment by TORISOUP** [comment]
I brought it to R3 because it is the operator schema that was available in UniRx, but was it not a good idea?

```cs
var s1 = new Subject<int>();
var s2 = new Subject<int>();
var s3 = new Subject<int>();

// Merge(this Observable<int>, params Observable<int>[])
s1.Merge(s2, s3).Subscribe();
```

**Comment by neuecc** [comment]
In that case `Observable.Merge(s1, s2, s3)` would be better.
Unlike Concat and others, it is not an ordered join.

**Comment by TORISOUP** [comment]
I see, if the wording is misleading, it would be better not to add it.

And the addition of the `public static Observable<T> Merge<T>(this IEnumerable<Observable<T>> sources)` extension method solved some problems. Therefore, this PR is closed.

Thanks.

**Pull request closed without merging**
